// Generates education/at-a-glance.md from education/graphics/index.json (#283).
// The index is the one place that holds each graphic's takeaway sentence and its
// optional "do not skip" rule; the page, and anything else that wants one picture
// and one sentence per lesson (a deck, an export), reads it from there.
//
//   node scripts/education-glance.mjs          # rewrite education/at-a-glance.md
//   node scripts/education-glance.mjs --check  # exit 1 if the page is out of date
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const EDUCATION = join(ROOT, 'education');

export const TIERS = {
  0: 'Before you start',
  1: 'Beginners',
  2: 'Intermediate',
  3: 'Advanced',
  4: 'Next step',
};

export function moduleLabel(page) {
  const match = /module-(\d+)-(\d+)-/.exec(page);
  return match ? `Module ${match[1]}.${match[2]}` : page;
}

export function tierOf(page) {
  return Number(page.split('/')[0].split('_')[0]);
}

// "Module 4.1" for a page with one graphic, "Module 4.1 (part 1 of 2)" for a page
// with several, so two entries for one module do not read as a duplicate.
export function entryLabels(index) {
  const total = {};
  for (const entry of index) total[entry.page] = (total[entry.page] ?? 0) + 1;
  const seen = {};
  return index.map((entry) => {
    seen[entry.page] = (seen[entry.page] ?? 0) + 1;
    const label = moduleLabel(entry.page);
    return total[entry.page] > 1 ? `${label} (part ${seen[entry.page]} of ${total[entry.page]})` : label;
  });
}

export function renderGlance(index, readHeading) {
  const labels = entryLabels(index);
  const lines = [
    '# At a glance',
    '',
    '<!-- Generated by scripts/education-glance.mjs from graphics/index.json. Do not edit by hand; run `npm run glance`. -->',
    '',
    'One picture and one sentence for each lesson page, grouped by tier. This is the',
    'five-minute version: it reminds you what a module is about, it does not replace',
    'it. **The module text is the source of truth.** If a sentence here and a module',
    'ever disagree, the module wins. Where a rule matters, the entry says **Do not',
    'skip**, and you should read that module before you act on it.',
    '',
  ];
  for (const [tier, name] of Object.entries(TIERS)) {
    const inTier = index.filter((entry) => tierOf(entry.page) === Number(tier));
    if (inTier.length === 0) continue;
    lines.push(`## ${name}`, '');
    for (const entry of inTier) {
      lines.push(
        // A heading may not end in punctuation (markdownlint MD026).
        `### ${labels[index.indexOf(entry)]}: ${entry.title.replace(/[.:;,!]+$/, '')}`,
        '',
        `![${entry.alt}](graphics/${entry.file})`,
        '',
        `**In one sentence:** ${entry.takeaway}`,
        '',
      );
      if (entry.rule) lines.push(`**Do not skip:** ${entry.rule}`, '');
      lines.push(`Read the module: [${readHeading(entry.page)}](${entry.page})`, '');
    }
  }
  lines.push('---', '', 'Back to the [education README](README.md).', '');
  return lines.join('\n');
}

export function readIndex() {
  return JSON.parse(readFileSync(join(EDUCATION, 'graphics', 'index.json'), 'utf8'));
}

export function readPageHeading(page) {
  const first = readFileSync(join(EDUCATION, page), 'utf8').split(/\r?\n/)[0];
  return first.replace(/^#\s*/, '').trim();
}

export function currentGlance() {
  return renderGlance(readIndex(), readPageHeading);
}

const invokedDirectly = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (invokedDirectly) {
  const target = join(EDUCATION, 'at-a-glance.md');
  const expected = currentGlance();
  if (process.argv.includes('--check')) {
    let actual = '';
    try {
      actual = readFileSync(target, 'utf8');
    } catch {
      // A missing page counts as out of date.
    }
    if (actual.replace(/\r\n/g, '\n') !== expected) {
      console.error('education/at-a-glance.md is out of date. Run `npm run glance`.');
      process.exit(1);
    }
    console.log('education/at-a-glance.md is up to date.');
  } else {
    writeFileSync(target, expected);
    console.log(`Wrote ${target}`);
  }
}
